services:
  db: # Dockerfile을 이용하지 않고 이미지를 바로 사용한다
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # root 사용자의 비밀번호
      MYSQL_DATABASE: project    # 생성할 데이터베이스 이름
      MYSQL_USER: root           # 사용자 계정 이름
      MYSQL_PASSWORD: 1234       # 사용자 비밀번호
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql    # 데이터를 저장할 로컬 디렉토리
    ports:
      - "3307:3306"                             # 포트 매핑 설정
  app:
    build: # build의 다음 명령어에 대해 root를 현재 디렉토리로 설정한다.
      context: /
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_NAME=project
      - DB_USERNAME=user
      - DB_PASSWORD=1234
    depends_on: #의존성을 설정하며 db 컨테이너가 실행된 후에 실행된다
      - db
    ports: # docker 외부 포트 : docker 포트 로 매핑한다
      - "3005:3005"

